### ISSUE TITLE
Error: EEXIST: file already exists

### ISSUE THREAD

**Issue by TyNguyen2k1** [ChristianChiarulli/nvim#103] opened 2021-01-12 09:33 UTC
Coc-bookmark not working

![Screenshot_20210112_105721](https://user-images.githubusercontent.com/64082226/104295988-b4151a00-54f3-11eb-8126-2b96880fa663.png)

### COC_INFO
```
## versions


vim version: NVIM v0.5.0-dev

node version: v14.15.0
coc.nvim version: 0.0.80-907fd17d34
coc.nvim directory: /home/ty/.config/nvim/autoload/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2021-01-12T16:27:03.160 INFO (pid:12444) [services] - registered service "languageserver.lua"
2021-01-12T16:27:03.556 ERROR (pid:12444) [server] - unhandledRejection  Promise {
  <rejected> [Error: EEXIST: file already exists, mkdir '/home/ty/.config/coc/extensions/coc-bookmark-data/bookmark.json'] {
    errno: -17,
    code: 'EEXIST',
    syscall: 'mkdir',
    path: '/home/ty/.config/coc/extensions/coc-bookmark-data/bookmark.json'
  }
} [Error: EEXIST: file already exists, mkdir '/home/ty/.config/coc/extensions/coc-bookmark-data/bookmark.json'] {
  errno: -17,
  code: 'EEXIST',
  syscall: 'mkdir',
  path: '/home/ty/.config/coc/extensions/coc-bookmark-data/bookmark.json'
}
2021-01-12T16:27:04.028 INFO (pid:12444) [services] - registered service "stylelintplus"
2021-01-12T16:27:04.068 INFO (pid:12444) [plugin] - coc.nvim 0.0.80-907fd17d34 initialized with node: v14.15.0 after 1052ms
2021-01-12T16:27:04.072 INFO (pid:12444) [attach] - receive notification: runCommand [ 'fzf-preview.Initialized' ]
2021-01-12T16:27:05.470 INFO (pid:12444) [attach] - receive notification: highlight []
2021-01-12T16:27:06.845 INFO (pid:12444) [attach] - receive notification: highlight []
2021-01-12T16:27:13.073 INFO (pid:12444) [attach] - receive notification: showInfo []


```
Thank you for help !!!

**Comment by eddyekofo94** [comment] 2021-01-12 12:36
it looks like this file `'/home/ty/.config/coc/extensions/coc-bookmark-data/bookmark.json'` already exists, try` :PlugClean` & `:PlugInstall`

**Comment by TyNguyen2k1** [comment] 2021-01-12 13:31
@eddyekofo94 it still doesn't work

**Comment by eddyekofo94** [comment] 2021-01-12 13:35
Manually delete the file? Maybe that'll work? It's saying that the file already exists... so it can't install. Therefore delete the folder: `/home/ty/.config/coc/extensions/coc-bookmark-data/`

**Comment by TyNguyen2k1** [comment] 2021-01-12 13:40
@eddyekofo94 I tried this one, it doesn't work either

**Comment by eddyekofo94** [comment] 2021-01-12 13:42
Is your project public? I'm in able to access it?

**Comment by TyNguyen2k1** [comment] 2021-01-12 13:47
@eddyekofo94 I install it with one command. I do not fix anything.

**Comment by eddyekofo94** [comment] 2021-01-12 13:48
Perfect then! Close the issue?

**Comment by TyNguyen2k1** [comment] 2021-01-12 13:55
@eddyekofo94 https://github.com/TyNguyen2k1/NVCode It here

**Comment by eddyekofo94** [comment] 2021-01-12 14:28
Cloned your project, ran `CocInstall coc-bookmark` it installed and everything worked fine. I can't reproduce the error. Sorry.

**Comment by TyNguyen2k1** [comment] 2021-01-12 15:05
@eddyekofo94 I replaced the bookmark.json folder with the bookmark.json file and it worked. But I have a new problem, the file bookmark.json is not recorded. Bookmarks only work when I open neovim

**Comment by eddyekofo94** [comment] 2021-01-12 21:34
Maybe this should be addressed to the plug-in itself and not here?

**Comment by soerenmartius** [comment] 2021-01-14 01:14
I am experiencing the same issue.

**Comment by F34th3R** [comment] 2021-01-14 04:55
I have the same issue, but, I'm trying to fix it too.

**Comment by AlanJui** [comment] 2021-01-15 14:40
1. list files under coc-bookmark-data, find bookmark.json is a directory not a file
```
$ ls -al ~/.config/coc/extensions/coc-bookmark-data
總用量 12
drwxr-xr-x 3 alanjui alanjui 4096  1月 15 22:24 .
drwxr-xr-x 5 alanjui alanjui 4096  1月 15 22:24 ..
drwxr-xr-x 2 alanjui alanjui 4096  1月 15 22:24 bookmark.json
```

2. remove the dir: 'bookmark.json'
```
$ rm -r ~/.config/coc/extensions/coc-bookmark-data/bookmark.json
```

3. create a json file named: 'bookmark.json'
```
touch ~/.config/coc/extensions/coc-bookmark-data/bookmark.json
```

4. edit file: bookmark.json and add outline format of json file
```
vim ~/.config/coc/extensions/coc-bookmark-data/bookmark.json 
```

contents in bookmark.json: 
```
{
}
```

**Comment by TyNguyen2k1** [comment] 2021-01-15 15:43
> 1. list files under coc-bookmark-data, find bookmark.json is a directory not a file
> 
> ```
> $ ls -al ~/.config/coc/extensions/coc-bookmark-data
> 總用量 12
> drwxr-xr-x 3 alanjui alanjui 4096  1月 15 22:24 .
> drwxr-xr-x 5 alanjui alanjui 4096  1月 15 22:24 ..
> drwxr-xr-x 2 alanjui alanjui 4096  1月 15 22:24 bookmark.json
> ```
> 
> 1. remove the dir: 'bookmark.json'
> 
> ```
> $ rm -r ~/.config/coc/extensions/coc-bookmark-data/bookmark.json
> ```
> 
> 1. create a json file named: 'bookmark.json'
> 
> ```
> touch ~/.config/coc/extensions/coc-bookmark-data/bookmark.json
> ```
> 
> 1. edit file: bookmark.json and add outline format of json file
> 
> ```
> vim ~/.config/coc/extensions/coc-bookmark-data/bookmark.json 
> ```
> 
> contents in bookmark.json:
> 
> ```
> {
> }
> ```

**Comment by TyNguyen2k1** [comment] 2021-01-15 15:45
> @eddyekofo94 I replaced the bookmark.json folder with the bookmark.json file and it worked. But I have a new problem, the file bookmark.json is not recorded. Bookmarks only work when I open neovim

Do you know this problem ?

**Comment by cadenforrest** [comment] 2021-01-16 09:07
> 1. list files under coc-bookmark-data, find bookmark.json is a directory not a file
> 
> ```
> $ ls -al ~/.config/coc/extensions/coc-bookmark-data
> 總用量 12
> drwxr-xr-x 3 alanjui alanjui 4096  1月 15 22:24 .
> drwxr-xr-x 5 alanjui alanjui 4096  1月 15 22:24 ..
> drwxr-xr-x 2 alanjui alanjui 4096  1月 15 22:24 bookmark.json
> ```
> 
> 1. remove the dir: 'bookmark.json'
> 
> ```
> $ rm -r ~/.config/coc/extensions/coc-bookmark-data/bookmark.json
> ```
> 
> 1. create a json file named: 'bookmark.json'
> 
> ```
> touch ~/.config/coc/extensions/coc-bookmark-data/bookmark.json
> ```
> 
> 1. edit file: bookmark.json and add outline format of json file
> 
> ```
> vim ~/.config/coc/extensions/coc-bookmark-data/bookmark.json 
> ```
> 
> contents in bookmark.json:
> 
> ```
> {
> }
> ```

This worked for me, I had @TyNguyen2k1 's original issue.

**Comment by ChristianChiarulli** [comment] 2021-03-10 09:04
CoC is completely removed so...

**Closed by ChristianChiarulli** 2021-03-10 09:04 UTC
